### Bibliotecas

In [1]:
import numpy as np


In [5]:
lista = [1,2,3,4,5,6,7,8,9,10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arreglo2 = np.array (lista1)
arreglo2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(arreglo)

numpy.ndarray

In [10]:
arreglo.dtype

dtype('int64')

In [11]:
np.array(arreglo, dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [13]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [15]:
arreglo.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
promedio = np.mean(arreglo)
promedio

5.5

In [19]:
mediana =np.median(arreglo)
mediana

5.5

In [20]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

In [22]:
arreglo_de_unos = np.ones(30)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
arreglo_de_ceros = np.zeros(4)
arreglo_de_ceros

array([0., 0., 0., 0.])

In [24]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.23259953, 0.96485174, 0.41862624, 0.65128771, 0.64800092,
       0.00898896, 0.43824899, 0.47855473, 0.24217786, 0.07575597])

In [25]:
arreglo_aleatorio2 = np.random.randint(1,200,10)
arreglo_aleatorio2

array([121,  52, 128, 187,  28, 153,  77,  50,  14, 148])

In [26]:
matriz = np.random.rand(3,3)
matriz

array([[0.68301921, 0.29685818, 0.80677149],
       [0.53146704, 0.62238983, 0.7147313 ],
       [0.9022643 , 0.5190772 , 0.80530619]])

In [27]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 91,  73,  60,  26,  44,  37,  60,  17,  54,  60],
       [100,  54,  53,  20,  66,  68,   4,  51,  18,  31],
       [ 84,  17,  86,  29,  17,  28,  87,  59,  55,  27],
       [ 30,   4,  42,  44,  71,  19,  81,  58,  33,  58],
       [  2,   3,  66,  57,  48,  80,  90,  43,  47,  12],
       [ 27,  97,   5,  48,  26,  14,   8,  32,  77,   3],
       [ 86,  51,  69,  45,  22, 100,  64,  81,  85,  53],
       [ 63,  22,  35,  30,  52,  95,  89,  22,  88,  63],
       [ 73,  37,  18,  94,  43,  78,  41,  17,   5,  99],
       [ 20,  64,  93,  38,  21,  79,  22,  73,  48,   3]])